#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosProductos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ecommerce")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertCalificacion(Calificacion instance);
    partial void UpdateCalificacion(Calificacion instance);
    partial void DeleteCalificacion(Calificacion instance);
    partial void InsertColor(Color instance);
    partial void UpdateColor(Color instance);
    partial void DeleteColor(Color instance);
    partial void InsertMarca(Marca instance);
    partial void UpdateMarca(Marca instance);
    partial void DeleteMarca(Marca instance);
    partial void InsertPromocion(Promocion instance);
    partial void UpdatePromocion(Promocion instance);
    partial void DeletePromocion(Promocion instance);
    partial void InsertSexo(Sexo instance);
    partial void UpdateSexo(Sexo instance);
    partial void DeleteSexo(Sexo instance);
    partial void InsertTalle(Talle instance);
    partial void UpdateTalle(Talle instance);
    partial void DeleteTalle(Talle instance);
    partial void InsertTemporada(Temporada instance);
    partial void UpdateTemporada(Temporada instance);
    partial void DeleteTemporada(Temporada instance);
    partial void InsertTipo(Tipo instance);
    partial void UpdateTipo(Tipo instance);
    partial void DeleteTipo(Tipo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DatosProductos.Properties.Settings.Default.EcommerceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Calificacion> Calificacion
		{
			get
			{
				return this.GetTable<Calificacion>();
			}
		}
		
		public System.Data.Linq.Table<Color> Color
		{
			get
			{
				return this.GetTable<Color>();
			}
		}
		
		public System.Data.Linq.Table<Marca> Marca
		{
			get
			{
				return this.GetTable<Marca>();
			}
		}
		
		public System.Data.Linq.Table<Promocion> Promocion
		{
			get
			{
				return this.GetTable<Promocion>();
			}
		}
		
		public System.Data.Linq.Table<Sexo> Sexo
		{
			get
			{
				return this.GetTable<Sexo>();
			}
		}
		
		public System.Data.Linq.Table<Talle> Talle
		{
			get
			{
				return this.GetTable<Talle>();
			}
		}
		
		public System.Data.Linq.Table<Temporada> Temporada
		{
			get
			{
				return this.GetTable<Temporada>();
			}
		}
		
		public System.Data.Linq.Table<Tipo> Tipo
		{
			get
			{
				return this.GetTable<Tipo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminaProducto")]
		public int eliminaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarProducto")]
		public ISingleResult<mostrarProductoResult> mostrarProducto()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarProducto")]
		public int insertarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fechaDeAlta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMarca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTemporada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idColor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTalle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPromocion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCalificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string imagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombreProducto, descripcion, precio, stock, fechaDeAlta, idMarca, idTipo, idTemporada, idSexo, idColor, idTalle, idPromocion, idCalificacion, imagen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificaProducto")]
		public int modificaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fechaDeAlta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMarca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTemporada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idColor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTalle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPromocion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCalificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string imagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombreProducto, descripcion, precio, stock, fechaDeAlta, idMarca, idTipo, idTemporada, idSexo, idColor, idTalle, idPromocion, idCalificacion, imagen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarProductos")]
		public int actualizarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fechaDeAlta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMarca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTemporada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idColor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTalle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPromocion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCalificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string imagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombreProducto, descripcion, precio, stock, fechaDeAlta, idMarca, idTipo, idTemporada, idSexo, idColor, idTalle, idPromocion, idCalificacion, imagen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerProductos")]
		public ISingleResult<obtenerProductosResult> obtenerProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerProductosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo;
		
		private string _nombreProducto;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _stock;
		
		private string _fechaDeAlta;
		
		private System.Nullable<int> _idMarca;
		
		private System.Nullable<int> _idTipo;
		
		private System.Nullable<int> _idTemporada;
		
		private System.Nullable<int> _idSexo;
		
		private System.Nullable<int> _idColor;
		
		private System.Nullable<int> _idTalle;
		
		private System.Nullable<int> _idPromocion;
		
		private System.Nullable<int> _idCalificacion;
		
		private string _imagen;
		
		private EntityRef<Calificacion> _Calificacion;
		
		private EntityRef<Color> _Color;
		
		private EntityRef<Marca> _Marca;
		
		private EntityRef<Promocion> _Promocion;
		
		private EntityRef<Sexo> _Sexo;
		
		private EntityRef<Talle> _Talle;
		
		private EntityRef<Temporada> _Temporada;
		
		private EntityRef<Tipo> _Tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnnombreProductoChanging(string value);
    partial void OnnombreProductoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnstockChanging(System.Nullable<int> value);
    partial void OnstockChanged();
    partial void OnfechaDeAltaChanging(string value);
    partial void OnfechaDeAltaChanged();
    partial void OnidMarcaChanging(System.Nullable<int> value);
    partial void OnidMarcaChanged();
    partial void OnidTipoChanging(System.Nullable<int> value);
    partial void OnidTipoChanged();
    partial void OnidTemporadaChanging(System.Nullable<int> value);
    partial void OnidTemporadaChanged();
    partial void OnidSexoChanging(System.Nullable<int> value);
    partial void OnidSexoChanged();
    partial void OnidColorChanging(System.Nullable<int> value);
    partial void OnidColorChanged();
    partial void OnidTalleChanging(System.Nullable<int> value);
    partial void OnidTalleChanged();
    partial void OnidPromocionChanging(System.Nullable<int> value);
    partial void OnidPromocionChanged();
    partial void OnidCalificacionChanging(System.Nullable<int> value);
    partial void OnidCalificacionChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    #endregion
		
		public Producto()
		{
			this._Calificacion = default(EntityRef<Calificacion>);
			this._Color = default(EntityRef<Color>);
			this._Marca = default(EntityRef<Marca>);
			this._Promocion = default(EntityRef<Promocion>);
			this._Sexo = default(EntityRef<Sexo>);
			this._Talle = default(EntityRef<Talle>);
			this._Temporada = default(EntityRef<Temporada>);
			this._Tipo = default(EntityRef<Tipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="NVarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this.OnnombreProductoChanging(value);
					this.SendPropertyChanging();
					this._nombreProducto = value;
					this.SendPropertyChanged("nombreProducto");
					this.OnnombreProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
		public System.Nullable<int> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaDeAlta", DbType="NVarChar(50)")]
		public string fechaDeAlta
		{
			get
			{
				return this._fechaDeAlta;
			}
			set
			{
				if ((this._fechaDeAlta != value))
				{
					this.OnfechaDeAltaChanging(value);
					this.SendPropertyChanging();
					this._fechaDeAlta = value;
					this.SendPropertyChanged("fechaDeAlta");
					this.OnfechaDeAltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarca", DbType="Int")]
		public System.Nullable<int> idMarca
		{
			get
			{
				return this._idMarca;
			}
			set
			{
				if ((this._idMarca != value))
				{
					if (this._Marca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMarcaChanging(value);
					this.SendPropertyChanging();
					this._idMarca = value;
					this.SendPropertyChanged("idMarca");
					this.OnidMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo", DbType="Int")]
		public System.Nullable<int> idTipo
		{
			get
			{
				return this._idTipo;
			}
			set
			{
				if ((this._idTipo != value))
				{
					if (this._Tipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoChanging(value);
					this.SendPropertyChanging();
					this._idTipo = value;
					this.SendPropertyChanged("idTipo");
					this.OnidTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTemporada", DbType="Int")]
		public System.Nullable<int> idTemporada
		{
			get
			{
				return this._idTemporada;
			}
			set
			{
				if ((this._idTemporada != value))
				{
					if (this._Temporada.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTemporadaChanging(value);
					this.SendPropertyChanging();
					this._idTemporada = value;
					this.SendPropertyChanged("idTemporada");
					this.OnidTemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSexo", DbType="Int")]
		public System.Nullable<int> idSexo
		{
			get
			{
				return this._idSexo;
			}
			set
			{
				if ((this._idSexo != value))
				{
					if (this._Sexo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSexoChanging(value);
					this.SendPropertyChanging();
					this._idSexo = value;
					this.SendPropertyChanged("idSexo");
					this.OnidSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idColor", DbType="Int")]
		public System.Nullable<int> idColor
		{
			get
			{
				return this._idColor;
			}
			set
			{
				if ((this._idColor != value))
				{
					if (this._Color.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidColorChanging(value);
					this.SendPropertyChanging();
					this._idColor = value;
					this.SendPropertyChanged("idColor");
					this.OnidColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTalle", DbType="Int")]
		public System.Nullable<int> idTalle
		{
			get
			{
				return this._idTalle;
			}
			set
			{
				if ((this._idTalle != value))
				{
					if (this._Talle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTalleChanging(value);
					this.SendPropertyChanging();
					this._idTalle = value;
					this.SendPropertyChanged("idTalle");
					this.OnidTalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPromocion", DbType="Int")]
		public System.Nullable<int> idPromocion
		{
			get
			{
				return this._idPromocion;
			}
			set
			{
				if ((this._idPromocion != value))
				{
					if (this._Promocion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPromocionChanging(value);
					this.SendPropertyChanging();
					this._idPromocion = value;
					this.SendPropertyChanged("idPromocion");
					this.OnidPromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCalificacion", DbType="Int")]
		public System.Nullable<int> idCalificacion
		{
			get
			{
				return this._idCalificacion;
			}
			set
			{
				if ((this._idCalificacion != value))
				{
					if (this._Calificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCalificacionChanging(value);
					this.SendPropertyChanging();
					this._idCalificacion = value;
					this.SendPropertyChanged("idCalificacion");
					this.OnidCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(250)")]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calificacion_Producto", Storage="_Calificacion", ThisKey="idCalificacion", OtherKey="id", IsForeignKey=true)]
		public Calificacion Calificacion
		{
			get
			{
				return this._Calificacion.Entity;
			}
			set
			{
				Calificacion previousValue = this._Calificacion.Entity;
				if (((previousValue != value) 
							|| (this._Calificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calificacion.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Calificacion.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idCalificacion = value.id;
					}
					else
					{
						this._idCalificacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Calificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Color_Producto", Storage="_Color", ThisKey="idColor", OtherKey="id", IsForeignKey=true)]
		public Color Color
		{
			get
			{
				return this._Color.Entity;
			}
			set
			{
				Color previousValue = this._Color.Entity;
				if (((previousValue != value) 
							|| (this._Color.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Color.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Color.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idColor = value.id;
					}
					else
					{
						this._idColor = default(Nullable<int>);
					}
					this.SendPropertyChanged("Color");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_Marca", ThisKey="idMarca", OtherKey="id", IsForeignKey=true)]
		public Marca Marca
		{
			get
			{
				return this._Marca.Entity;
			}
			set
			{
				Marca previousValue = this._Marca.Entity;
				if (((previousValue != value) 
							|| (this._Marca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Marca.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idMarca = value.id;
					}
					else
					{
						this._idMarca = default(Nullable<int>);
					}
					this.SendPropertyChanged("Marca");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promocion_Producto", Storage="_Promocion", ThisKey="idPromocion", OtherKey="id", IsForeignKey=true)]
		public Promocion Promocion
		{
			get
			{
				return this._Promocion.Entity;
			}
			set
			{
				Promocion previousValue = this._Promocion.Entity;
				if (((previousValue != value) 
							|| (this._Promocion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Promocion.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Promocion.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idPromocion = value.id;
					}
					else
					{
						this._idPromocion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Promocion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sexo_Producto", Storage="_Sexo", ThisKey="idSexo", OtherKey="id", IsForeignKey=true)]
		public Sexo Sexo
		{
			get
			{
				return this._Sexo.Entity;
			}
			set
			{
				Sexo previousValue = this._Sexo.Entity;
				if (((previousValue != value) 
							|| (this._Sexo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sexo.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Sexo.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idSexo = value.id;
					}
					else
					{
						this._idSexo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sexo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Talle_Producto", Storage="_Talle", ThisKey="idTalle", OtherKey="id", IsForeignKey=true)]
		public Talle Talle
		{
			get
			{
				return this._Talle.Entity;
			}
			set
			{
				Talle previousValue = this._Talle.Entity;
				if (((previousValue != value) 
							|| (this._Talle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Talle.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Talle.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idTalle = value.id;
					}
					else
					{
						this._idTalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("Talle");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Temporada_Producto", Storage="_Temporada", ThisKey="idTemporada", OtherKey="id", IsForeignKey=true)]
		public Temporada Temporada
		{
			get
			{
				return this._Temporada.Entity;
			}
			set
			{
				Temporada previousValue = this._Temporada.Entity;
				if (((previousValue != value) 
							|| (this._Temporada.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Temporada.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Temporada.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idTemporada = value.id;
					}
					else
					{
						this._idTemporada = default(Nullable<int>);
					}
					this.SendPropertyChanged("Temporada");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Producto", Storage="_Tipo", ThisKey="idTipo", OtherKey="id", IsForeignKey=true)]
		public Tipo Tipo
		{
			get
			{
				return this._Tipo.Entity;
			}
			set
			{
				Tipo previousValue = this._Tipo.Entity;
				if (((previousValue != value) 
							|| (this._Tipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Tipo.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._idTipo = value.id;
					}
					else
					{
						this._idTipo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tipo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calificacion")]
	public partial class Calificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _valoracion;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvaloracionChanging(string value);
    partial void OnvaloracionChanged();
    #endregion
		
		public Calificacion()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="NVarChar(50)")]
		public string valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this.OnvaloracionChanging(value);
					this.SendPropertyChanging();
					this._valoracion = value;
					this.SendPropertyChanged("valoracion");
					this.OnvaloracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calificacion_Producto", Storage="_Producto", ThisKey="id", OtherKey="idCalificacion")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Calificacion = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Calificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Color")]
	public partial class Color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreColor;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreColorChanging(string value);
    partial void OnnombreColorChanged();
    #endregion
		
		public Color()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreColor", DbType="NVarChar(50)")]
		public string nombreColor
		{
			get
			{
				return this._nombreColor;
			}
			set
			{
				if ((this._nombreColor != value))
				{
					this.OnnombreColorChanging(value);
					this.SendPropertyChanging();
					this._nombreColor = value;
					this.SendPropertyChanged("nombreColor");
					this.OnnombreColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Color_Producto", Storage="_Producto", ThisKey="id", OtherKey="idColor")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Color = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Color = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marca")]
	public partial class Marca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreMarca;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreMarcaChanging(string value);
    partial void OnnombreMarcaChanged();
    #endregion
		
		public Marca()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMarca", DbType="NVarChar(50)")]
		public string nombreMarca
		{
			get
			{
				return this._nombreMarca;
			}
			set
			{
				if ((this._nombreMarca != value))
				{
					this.OnnombreMarcaChanging(value);
					this.SendPropertyChanging();
					this._nombreMarca = value;
					this.SendPropertyChanged("nombreMarca");
					this.OnnombreMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_Producto", ThisKey="id", OtherKey="idMarca")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Marca = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Marca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Promocion")]
	public partial class Promocion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombrePromocion;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombrePromocionChanging(string value);
    partial void OnnombrePromocionChanged();
    #endregion
		
		public Promocion()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePromocion", DbType="NVarChar(50)")]
		public string nombrePromocion
		{
			get
			{
				return this._nombrePromocion;
			}
			set
			{
				if ((this._nombrePromocion != value))
				{
					this.OnnombrePromocionChanging(value);
					this.SendPropertyChanging();
					this._nombrePromocion = value;
					this.SendPropertyChanged("nombrePromocion");
					this.OnnombrePromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promocion_Producto", Storage="_Producto", ThisKey="id", OtherKey="idPromocion")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Promocion = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Promocion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sexo")]
	public partial class Sexo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreSexo;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreSexoChanging(string value);
    partial void OnnombreSexoChanged();
    #endregion
		
		public Sexo()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreSexo", DbType="NVarChar(50)")]
		public string nombreSexo
		{
			get
			{
				return this._nombreSexo;
			}
			set
			{
				if ((this._nombreSexo != value))
				{
					this.OnnombreSexoChanging(value);
					this.SendPropertyChanging();
					this._nombreSexo = value;
					this.SendPropertyChanged("nombreSexo");
					this.OnnombreSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sexo_Producto", Storage="_Producto", ThisKey="id", OtherKey="idSexo")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Sexo = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Sexo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Talle")]
	public partial class Talle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _medida;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmedidaChanging(string value);
    partial void OnmedidaChanged();
    #endregion
		
		public Talle()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medida", DbType="NVarChar(50)")]
		public string medida
		{
			get
			{
				return this._medida;
			}
			set
			{
				if ((this._medida != value))
				{
					this.OnmedidaChanging(value);
					this.SendPropertyChanging();
					this._medida = value;
					this.SendPropertyChanged("medida");
					this.OnmedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Talle_Producto", Storage="_Producto", ThisKey="id", OtherKey="idTalle")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Talle = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Talle = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Temporada")]
	public partial class Temporada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreTemporada;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreTemporadaChanging(string value);
    partial void OnnombreTemporadaChanged();
    #endregion
		
		public Temporada()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTemporada", DbType="NVarChar(50)")]
		public string nombreTemporada
		{
			get
			{
				return this._nombreTemporada;
			}
			set
			{
				if ((this._nombreTemporada != value))
				{
					this.OnnombreTemporadaChanging(value);
					this.SendPropertyChanging();
					this._nombreTemporada = value;
					this.SendPropertyChanged("nombreTemporada");
					this.OnnombreTemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Temporada_Producto", Storage="_Producto", ThisKey="id", OtherKey="idTemporada")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Temporada = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Temporada = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo")]
	public partial class Tipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreTipo;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreTipoChanging(string value);
    partial void OnnombreTipoChanged();
    #endregion
		
		public Tipo()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTipo", DbType="NVarChar(50)")]
		public string nombreTipo
		{
			get
			{
				return this._nombreTipo;
			}
			set
			{
				if ((this._nombreTipo != value))
				{
					this.OnnombreTipoChanging(value);
					this.SendPropertyChanging();
					this._nombreTipo = value;
					this.SendPropertyChanged("nombreTipo");
					this.OnnombreTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Producto", Storage="_Producto", ThisKey="id", OtherKey="idTipo")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo = null;
		}
	}
	
	public partial class mostrarProductoResult
	{
		
		private string _codigo;
		
		private string _nombreProducto;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _stock;
		
		private string _nombreMarca;
		
		private string _nombreTipo;
		
		private string _nombreTemporada;
		
		private string _nombreSexo;
		
		private string _nombreColor;
		
		private string _medida;
		
		private string _nombrePromocion;
		
		private string _valoracion;
		
		private string _imagen;
		
		public mostrarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="NVarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
		public System.Nullable<int> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this._stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMarca", DbType="NVarChar(50)")]
		public string nombreMarca
		{
			get
			{
				return this._nombreMarca;
			}
			set
			{
				if ((this._nombreMarca != value))
				{
					this._nombreMarca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTipo", DbType="NVarChar(50)")]
		public string nombreTipo
		{
			get
			{
				return this._nombreTipo;
			}
			set
			{
				if ((this._nombreTipo != value))
				{
					this._nombreTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTemporada", DbType="NVarChar(50)")]
		public string nombreTemporada
		{
			get
			{
				return this._nombreTemporada;
			}
			set
			{
				if ((this._nombreTemporada != value))
				{
					this._nombreTemporada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreSexo", DbType="NVarChar(50)")]
		public string nombreSexo
		{
			get
			{
				return this._nombreSexo;
			}
			set
			{
				if ((this._nombreSexo != value))
				{
					this._nombreSexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreColor", DbType="NVarChar(50)")]
		public string nombreColor
		{
			get
			{
				return this._nombreColor;
			}
			set
			{
				if ((this._nombreColor != value))
				{
					this._nombreColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medida", DbType="NVarChar(50)")]
		public string medida
		{
			get
			{
				return this._medida;
			}
			set
			{
				if ((this._medida != value))
				{
					this._medida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePromocion", DbType="NVarChar(50)")]
		public string nombrePromocion
		{
			get
			{
				return this._nombrePromocion;
			}
			set
			{
				if ((this._nombrePromocion != value))
				{
					this._nombrePromocion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="NVarChar(50)")]
		public string valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this._valoracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(250)")]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this._imagen = value;
				}
			}
		}
	}
	
	public partial class obtenerProductosResult
	{
		
		private string _codigo;
		
		private string _nombreProducto;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _stock;
		
		private string _fechaDeAlta;
		
		private System.Nullable<int> _idMarca;
		
		private System.Nullable<int> _idTipo;
		
		private System.Nullable<int> _idTemporada;
		
		private System.Nullable<int> _idSexo;
		
		private System.Nullable<int> _idColor;
		
		private System.Nullable<int> _idTalle;
		
		private System.Nullable<int> _idPromocion;
		
		private System.Nullable<int> _idCalificacion;
		
		private string _imagen;
		
		public obtenerProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="NVarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
		public System.Nullable<int> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this._stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaDeAlta", DbType="NVarChar(50)")]
		public string fechaDeAlta
		{
			get
			{
				return this._fechaDeAlta;
			}
			set
			{
				if ((this._fechaDeAlta != value))
				{
					this._fechaDeAlta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarca", DbType="Int")]
		public System.Nullable<int> idMarca
		{
			get
			{
				return this._idMarca;
			}
			set
			{
				if ((this._idMarca != value))
				{
					this._idMarca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo", DbType="Int")]
		public System.Nullable<int> idTipo
		{
			get
			{
				return this._idTipo;
			}
			set
			{
				if ((this._idTipo != value))
				{
					this._idTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTemporada", DbType="Int")]
		public System.Nullable<int> idTemporada
		{
			get
			{
				return this._idTemporada;
			}
			set
			{
				if ((this._idTemporada != value))
				{
					this._idTemporada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSexo", DbType="Int")]
		public System.Nullable<int> idSexo
		{
			get
			{
				return this._idSexo;
			}
			set
			{
				if ((this._idSexo != value))
				{
					this._idSexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idColor", DbType="Int")]
		public System.Nullable<int> idColor
		{
			get
			{
				return this._idColor;
			}
			set
			{
				if ((this._idColor != value))
				{
					this._idColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTalle", DbType="Int")]
		public System.Nullable<int> idTalle
		{
			get
			{
				return this._idTalle;
			}
			set
			{
				if ((this._idTalle != value))
				{
					this._idTalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPromocion", DbType="Int")]
		public System.Nullable<int> idPromocion
		{
			get
			{
				return this._idPromocion;
			}
			set
			{
				if ((this._idPromocion != value))
				{
					this._idPromocion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCalificacion", DbType="Int")]
		public System.Nullable<int> idCalificacion
		{
			get
			{
				return this._idCalificacion;
			}
			set
			{
				if ((this._idCalificacion != value))
				{
					this._idCalificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(250)")]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this._imagen = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
